name: Docker Runner

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: self-hosted
    environment: production

    steps:
      - uses: actions/checkout@v2

      - name: Build Docker Image
        run: docker build -t weather-api .

      - name: Kill Previous Container
        continue-on-error: true
        run: docker rm -f weather-api

      - name: Start Docker Container
        run: docker run -d -p 5001:5001 -e APIKEY=$APIKEY -e PORT=5001 --name weather-api weather-api:latest
        env:
          APIKEY: ${{ secrets.TOKEN }}

  test:
    runs-on: self-hosted
    needs: build

    steps:

      - name: Update Requirements
        run: pip3 install -U pytest pytest-asyncio

      - name: Run Tests
        run: pytest tests/
